# Generated by Django 2.1 on 2020-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_runtime',
            field=models.CharField(default='python3.8', max_length=250),
        ),
    ]
