# Generated by Django 2.1 on 2020-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200531_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_runtime',
            field=models.CharField(default='', max_length=250),
        ),
    ]
