version: "3"
services:
  web:
    image: python:3
    build: .
    environment: PYTHONUNBUFFERED=1
    container_name: web_codeexpert
    volumes:
      - /home/codeexpert:/home/codeexpert
      - /home/ubuntu/challenges:/home/ubuntu/challenges
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "800:80"
    environment:
    - NGINX_HOST=codeexpert.dev
    - NGINX_PORT=80

