# Generated by Django 2.1 on 2020-05-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20200531_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='difficult',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
