# Generated by Django 2.1 on 2020-05-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_difficult'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code',
            field=models.TextField(null=True),
        ),
    ]
