# Generated by Django 2.1 on 2020-05-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_answer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficult',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
