# Generated by Django 2.1 on 2020-06-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20200531_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
